# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['client\\gui.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'pynput',
        'pynput.keyboard',
        'pynput.keyboard._win32',
        'pynput.mouse',
        'pynput.mouse._win32',
        'sounddevice',
        'websockets',
        'websockets.client',
        'websockets.exceptions',
        'httpx',
        'httpx._client',
        'httpx._transports',
        'httpx._transports.default',
        'httpcore',
        'httpcore._backends',
        'httpcore._backends.sync',
        'httpcore._backends.auto',
        'pyautogui',
        'pyperclip',
        'PySimpleGUI',
        'h11',
        'h11._abnf',
        'certifi',
        'ssl',
        'json',
        'asyncio',
        'threading',
        'queue',
        'base64',
        'datetime',
        'time',
        'typing',
        'logging',
        'os',
        'sys',
        'io',
        'struct',
        'wave',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='VoiceInputFramework',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # 设置为 True 可以看到错误信息
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
